from .base_config import *

ENV_ID = "Walker2d-v5"

SEGMENT_LEN = 50
INITIAL_SEGMENT_LEN = 50
FINAL_SEGMENT_LEN = 50

TOTAL_TARGET_PAIRS = 1000
TOTAL_PPO_TIMESTEPS = 5e6

# Reward model training hyperparameters
USE_REWARD_ENSEMBLES = False

FEEDBACK_TYPE = "evaluative"
EVALUATIVE_RATING_RANGE = (-30, 350)
EVALUATIVE_RATING_SCALE = None
USE_PROBABILISTIC_MODEL = True