from .base_config import *

ENV_ID = "Walker2d-v5"

SEGMENT_LEN = 200
INITIAL_SEGMENT_LEN = 200
FINAL_SEGMENT_LEN = 200

TOTAL_TARGET_PAIRS = 1500
TOTAL_PPO_TIMESTEPS = 3e6

# Reward model training hyperparameters
USE_REWARD_ENSEMBLES = False

FEEDBACK_TYPE = "evaluative"
EVALUATIVE_RATING_RANGE = (-200, 1500)
EVALUATIVE_RATING_SCALE = 10